### ISSUE TITLE
Debian has no package libjpeg-turbo8-dev

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos-linux#31]
If no package is found, it should default to the libjpeg-dev package instead.

**Comment by eskiiom** [comment]
it may come from a broken debian package, but the issue persists

`root@test:/tmp/librephotos-linux# ./install-librephotos.sh 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'liborc-0.4-dev' instead of 'liborc-dev'
liborc-0.4-dev is already the newest version (1:0.4.28-3.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libjpeg-turbo8-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source`

**Comment by hanscats** [comment]
install libjpeg62-turbo-dev instead

**Comment by nicopace** [comment]
> install libjpeg62-turbo-dev instead (edit the install script).

It would be great if it could be a conditional in the script (whether to use one or the other)
